{
 "title": "Health checks",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "healthcheck",
    "query": {
     "query": "label_values(healthcheck_total,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failed health checks",
   "type": "timeseries",
   "description": "Failed health checks rate (5 minutes)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (rate(healthcheck_total{status=\"failure\"}[5m]))",
     "legendFormat": "{{ name }} ({{ id }})"
    }
   ]
  },
  {
   "title": "Number of successful health checks execution",
   "type": "stat",
   "description": "Number of successful health check in the selected interval",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(healthcheck_total{status=\"success\"}[$__range]))",
     "legendFormat": "failures (last day)"
    }
   ]
  },
  {
   "title": "Number of failed health check execution",
   "type": "stat",
   "description": "Number of health checks failures in the selected interval",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(healthcheck_total{status=\"failure\"}[$__range]))",
     "legendFormat": "failures (last day)"
    }
   ]
  },
  { "title": "Health check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Success and failure execution rate",
   "type": "timeseries",
   "description": "Health check rate per seconds",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(healthcheck_total{name=\"$healthcheck\", status=\"failure\"}[5m]))",
     "legendFormat": "failure"
    },
    {
     "expr": "sum(rate(healthcheck_total{name=\"$healthcheck\", status=\"success\"}[5m]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Number of successful health check execution",
   "type": "stat",
   "description": "Number of successful health check in the selected interval",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(healthcheck_total{name=\"$healthcheck\", status=\"success\"}[$__range]))",
     "legendFormat": "failures (last day)"
    }
   ]
  },
  {
   "title": "Number of failed health check execution",
   "type": "stat",
   "description": "Number of health checks failures in the selected interval",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(healthcheck_total{name=\"$healthcheck\", status=\"failure\"}[$__range]))",
     "legendFormat": "failures (last day)"
    }
   ]
  },
  {
   "title": "Execution time",
   "type": "timeseries",
   "description": "Health check execution time quantiles",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(healthcheck_duration_seconds_bucket{name=\"$healthcheck\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(healthcheck_duration_seconds_bucket{name=\"$healthcheck\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(healthcheck_duration_seconds_bucket{name=\"$healthcheck\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Execution time Heat map",
   "type": "heatmap",
   "description": "Health check execution time Heat map",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(healthcheck_duration_seconds_bucket{name=\"$healthcheck\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}